name = "lab-reagent-system"
pages_build_output_dir = "public"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "lab-reagents-db"
database_id = "fff77ff0-0430-42f1-b288-514effc72f3f"
